### ISSUE TITLE
《kube-proxy ipvs 模式源码分析》一节的疑问，请指教

### ISSUE THREAD

**Issue by yaocw2020** [gosoon/source-code-reading-notes#1]
https://www.bookstack.cn/read/source-code-reading-notes/kubernetes-kube_proxy_ipvs.md
文章里谈到 "ipvs 还支持 realserver 运行状况检查"
http://www.tianfeiyu.com/?p=2010#title-3
但是您在这篇博客最后说 lvs 缺陷的时候说 “不能检测后端服务器的健康状况，总是发送连接到后端”，
想请教下这里具体情况下是怎么样子的？是需要什么配置吗？

=========================
另外，在 https://www.bookstack.cn/read/source-code-reading-notes/kubernetes-kube_proxy_ipvs.md 文章里您有一句是这么写的
“从 PREROUTING 链会转到 KUBE-SERVICES 链，10.244.0.0/16 为 ClusterIP 网段“
我在实际集群中看到，10.244.0.0/16 应该是集群 pod 所在的网段，而不是 ClusterIP 的网段，不知道我有没有搞错？

**Comment by gosoon** [comment]
"ipvs 还支持 realserver 运行状况检查"
ipvs 本身不支持检查 rs 状态，不过它支持配置插件或者脚本来检查后端 rs 状态；
“10.244.0.0/16 为 ClusterIP 网段”
 cluster ip 网段可以在 apiserver 中通过 `--service-cluster-ip-range` 指定，咱们的环境应该不一致

Canwu Yao <notifications@github.com> 于2020年5月10日周日 下午11:50写道：
