### ISSUE TITLE
您好，关于图片引用问题

### ISSUE THREAD

**Issue by googs1025** [gosoon/source-code-reading-notes#20]
雨飞大老，您好，最近我也在研究kubelet相关的内容，同时也拜读了您所写的源码分析，
让我对k8s的有更全面的认识。
目前我自己也会分享一些自己对k8s粗浅的理解 [pr在这](https://github.com/k8s-club/k8s-club/pull/54
)
其中，您博客的这张图片我想引用一下，请问可以嘛？同时我在文中也会备注出处。感谢抽空看 issue。

![image](https://github.com/gosoon/source-code-reading-notes/assets/86391540/d906a89c-22e5-4554-9258-dbe55281b1b5)

**Comment by gosoon** [comment]
可以的
