### ISSUE TITLE
有联系方式吗？交个朋友。加个微信

### ISSUE THREAD

**Issue by standup-jb** [gosoon/source-code-reading-notes#4]

**Comment by gosoon** [comment]
可以留一下你的联系方式，我加你

**Comment by standup-jb** [comment]
13368283610



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tianfeiyu <notifications@github.com&gt;
发送时间: 2021年1月29日 10:21
收件人: gosoon/source-code-reading-notes <source-code-reading-notes@noreply.github.com&gt;
抄送: Jiang Biao <862486382@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[gosoon/source-code-reading-notes] 有联系方式吗？交个朋友。加个微信 (#4)





 
可以留一下你的联系方式，我加你
